(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition parse {A : Set} : A :=
  let p_value {B : Set} : B :=
    op_startypeminuserrorstar
      (op_startypeminuserrorstar (op_startypeminuserrorstar "#" % char)
        op_startypeminuserrorstar)
      (fun (function_parameter : option C) =>
        match function_parameter with
        | None => op_startypeminuserrorstar [ op_startypeminuserrorstar ]
        | Some c_value =>
          if
            orb (op_startypeminuserrorstar c_value)
              (op_startypeminuserrorstar c_value)
          then
            op_startypeminuserrorstar
              (op_startypeminuserrorstar op_startypeminuserrorstar)
              (fun (line : option string) =>
                let line :=
                  match line with
                  | None => ""
                  | Some s_value => s_value
                  end in
                op_startypeminuserrorstar [ op_startypeminuserrorstar ])
          else
            op_startypeminuserrorstar "comment"
        end) in
  op_startypeminuserrorstar p_value.
