(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition parse {A : Set} : A :=
  let p_value {B : Set} : B :=
    op_startypeminuserrorstar
      (fun (name : C) => fun (value : C) => [ op_startypeminuserrorstar ])
      (op_startypeminuserrorstar "#+" ":"
        (op_startypeminuserrorstar
          (fun (c_value : ascii) =>
            andb (nequiv_decb c_value ":" % char)
              (op_startypeminuserrorstar c_value))))
      (op_startypeminuserrorstar op_startypeminuserrorstar
        op_startypeminuserrorstar) in
  op_startypeminuserrorstar p_value.
