(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition end_mark : string := ":END:".

Definition parse_properties : list string -> list (string * string) :=
  Stdlib.List.fold_left
    (fun (acc : list (string * string)) =>
      fun (line : string) =>
        (* âŒ Try-with are not handled *)
        try_with
          (fun _ =>
            Stdlib.Scanf.sscanf (Stdlib.String.trim line)
              (CamlinternalFormatBasics.Format
                (CamlinternalFormatBasics.Char_literal ":" % char
                  (CamlinternalFormatBasics.Scan_char_set None
                    "ÿÿÿÿÿÿÿûÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ"
                    (CamlinternalFormatBasics.String_literal ": "
                      (CamlinternalFormatBasics.Scan_char_set None
                        "ÿûÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ"
                        CamlinternalFormatBasics.End_of_format))))
                ":%[^:]: %[^" ++ String.String "010" "]")
              (fun (key : string) =>
                fun (value : string) => cons (key, value) acc))
          (fun _ =>
            match acc with
            | [] => acc
            | cons (key, v_value) acc' =>
              let line := String.append " " (Stdlib.String.trim line) in
              cons (key, (String.append v_value line)) acc'
            end)) nil.

Definition parse {A : Set} : A :=
  let drawer_name {B : Set} : B :=
    op_startypeminuserrorstar
      (op_startypeminuserrorstar op_startypeminuserrorstar
        (op_startypeminuserrorstar ":" % char ":" % char
          (op_startypeminuserrorstar
            (fun (c_value : ascii) => nequiv_decb c_value ":" % char))))
      op_startypeminuserrorstar in
  let drawer_body {B : Set} : B :=
    op_startypeminuserrorstar (fun (line : string) => equiv_decb line end_mark)
      "drawer body" in
  let p_value {B : Set} : B :=
    op_startypeminuserrorstar
      (fun (name : string) =>
        fun (body : list string) =>
          let drawer {C : Set} : C :=
            match name with
            | "PROPERTIES" =>
              let properties := parse_properties body in
              op_startypeminuserrorstar
            | _ => op_startypeminuserrorstar
            end in
          [ drawer ]) drawer_name drawer_body in
  op_startypeminuserrorstar p_value.
