(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition parse {A : Set} : A :=
  let p_value {B : Set} : B :=
    op_startypeminuserrorstar
      (op_startypeminuserrorstar 5 (op_startypeminuserrorstar "-" % char))
      (fun (function_parameter : C) =>
        let '_ := function_parameter in
        op_startypeminuserrorstar [ op_startypeminuserrorstar ]) in
  op_startypeminuserrorstar p_value.
