(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition env_name_options_parser {A : Set} : A :=
  op_startypeminuserrorstar
    (op_startypeminuserrorstar
      (fun (name : B) =>
        fun (options : option string) =>
          match options with
          | (None | Some "") => (name, None)
          | _ => (name, options)
          end)
      (op_startypeminuserrorstar
        (op_startypeminuserrorstar (op_startypeminuserrorstar "\begin{")
          (op_startypeminuserrorstar
            (fun (c_value : ascii) => nequiv_decb c_value "}" % char)))
        (op_startypeminuserrorstar "}" % char))
      (op_startypeminuserrorstar op_startypeminuserrorstar))
    op_startypeminuserrorstar.

Definition parse {A : Set} : A :=
  let p_value {B : Set} : B :=
    op_startypeminuserrorstar op_startypeminuserrorstar
      (fun (function_parameter : ascii) =>
        match function_parameter with
        | "\" % char =>
          op_startypeminuserrorstar env_name_options_parser
            (fun (function_parameter : string * C) =>
              let '(name, options) := function_parameter in
              op_startypeminuserrorstar
                (op_startypeminuserrorstar
                  (fun (line : C) =>
                    let prefix := String.append "\end{" (String.append name "}")
                      in
                    op_startypeminuserrorstar line prefix)
                  "Latex_environment body")
                (fun (lines : C) =>
                  op_startypeminuserrorstar [ op_startypeminuserrorstar ]))
        | _ =>
          op_startypeminuserrorstar op_startypeminuserrorstar
            op_startypeminuserrorstar
        end) in
  op_startypeminuserrorstar p_value.
