(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition ast_to_json {A B : Set} (ast : A) : B :=
  op_startypeminuserrorstar (op_startypeminuserrorstar ast).

Definition generate {A B C D E : Set}
  (backend : A) (config : B) (doc : C) (output : D) : E :=
  let export {F : Set} : F :=
    op_startypeminuserrorstar backend in
  op_startypeminuserrorstar export config doc output.


