(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Module t.
  Record record : Set := Build {
    toc : bool;
    heading_number : bool;
    keep_line_break : bool;
  }.
  Definition with_toc toc (r : record) :=
    Build toc r.(heading_number) r.(keep_line_break).
  Definition with_heading_number heading_number (r : record) :=
    Build r.(toc) heading_number r.(keep_line_break).
  Definition with_keep_line_break keep_line_break (r : record) :=
    Build r.(toc) r.(heading_number) keep_line_break.
End t.
Definition t := t.record.
