(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Module Document := Document.

Module Block := Block.

Module Inline := Inline.

Module Exporters.

End Exporters.

Module Conf := Conf.

Module Exporter := Exporter.

Module Timestamp := Timestamp.

Module Parser := Org_parser.

Module _Type := _Type.

Module Backends.
  Module Html := Html.
End Backends.

Module Xml := Xml.
